#!/usr/bin/env python
# -*- coding:utf-8 -*-

CLASS_PROMPTS = {  # class: [synonyms]
    "car": [
        "car",
        "automobile",
        "minivan",
        "auto",
        "sports car",
        "police car",
        "taxi",
        "SUV",
        "limousine",
        "luxury car",
        "off-road car",
        "BMW",
        "Mercedes",
        "Volkswagen",
        "Hyundai",
        "Kia",
        "Toyota",
        "Porsche",
        "Lamborghini",
        "Ferrari",
        "Ford",
        "General Motors",
        "Chevrolet",
        "Corvette",
        "Honda",
        "Nissan",
        "Fiat",
        "Jeep",
        "Volvo",
        "Rolls Royce",
        "Bentley",
        "Renault",
        "Audi",
        "Land Rover",
        "Lexus",
    ],
    "bicycle": [
        "bicycle",
        "mountain bike",
        "trail bike",
    ],
    "motorcycle": [
        "motorcycle",
        "motorbike",
        "dirt bike",
        "scooter",
        "chopper",
        "enduro",
        "vespa",
        "moped",
        "minibike",
        "harley davidson",
        "trike",
    ],
    "truck": [
        "truck",
        "lorry",
        "van",
        "semi-truck",
        "HGV",
        "transport vehicle",
        "dump truck",
        "garbage truck",
        "firetruck",
        "sprinter",
    ],
    "construction_vehicle": [
        "construction vehicle",
        "bulldozer",
        "forklift",
        "cherry picker",
        "mobile crane",
    ],
    "other_vehicle": [
        "ambulance",
        "john deere",
    ],
    "pedestrian": [
        "pedestrian",
        "man",
        "woman",
        "child",
        "kid",
        "human",
        "person",
    ],
    "bicyclist": [
        "biyclist",
        "cylist",
        "bike rider",
    ],
    "motorcyclist": [
        "motorcyclist",
        "motorbike rider",
        "scooter rider",
    ],
    "bus": [
        "bus",
        "school bus",
        "shuttle bus",
        "double-decker bus",
        "minibus",
        "coach",
    ],
}

HUMANS = [
    "pedestrian",
    "bicyclist",
    "motorcyclist",
]
